//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.example.mahua.funage.projection;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.CompoundButton;
import android.widget.CompoundButton.OnCheckedChangeListener;
import android.widget.ProgressBar;
import android.widget.TextView;
import android.widget.ToggleButton;
import com.example.mahua.funage.api.MyPrefs_;
import com.example.mahua.funage.application.MyApplication_;
import com.example.mahua.funage.projection.R.id;
import com.example.mahua.funage.projection.R.layout;
import com.example.mahua.funage.utils.VolleyTools_;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class FunctionActivity_
    extends FunctionActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_function);
    }

    private void init_(Bundle savedInstanceState) {
        sp = new MyPrefs_(this);
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        myApplication = MyApplication_.getInstance();
        volleyTools = VolleyTools_.getInstance_(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static FunctionActivity_.IntentBuilder_ intent(Context context) {
        return new FunctionActivity_.IntentBuilder_(context);
    }

    public static FunctionActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new FunctionActivity_.IntentBuilder_(fragment);
    }

    public static FunctionActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new FunctionActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        pb = ((ProgressBar) hasViews.findViewById(id.pb));
        tv_name = ((TextView) hasViews.findViewById(id.tv_name));
        progressBar1 = ((ProgressBar) hasViews.findViewById(id.progressBar1));
        tv_progress = ((TextView) hasViews.findViewById(id.tv_progress));
        tb = ((ToggleButton) hasViews.findViewById(id.tb));
        tv_time = ((TextView) hasViews.findViewById(id.tv_time));
        {
            View view = hasViews.findViewById(id.onInputCard);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        FunctionActivity_.this.onInputCard(view);
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.qrbtn);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        FunctionActivity_.this.onQRScan(view);
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.onMessageScan);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        FunctionActivity_.this.onMessageScan(view);
                    }

                }
                );
            }
        }
        {
            CompoundButton view = ((CompoundButton) hasViews.findViewById(id.tb));
            if (view!= null) {
                view.setOnCheckedChangeListener(new OnCheckedChangeListener() {


                    @Override
                    public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
                        FunctionActivity_.this.checkedChangeOnPersonCardCheckBox(buttonView, isChecked);
                    }

                }
                );
            }
        }
        initView();
        init();
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, FunctionActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, FunctionActivity_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, FunctionActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public FunctionActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

    }

}
