//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.example.mahua.funage.projection;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.AdapterView;
import android.widget.AdapterView.OnItemClickListener;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.TextView;
import com.example.mahua.funage.application.MyApplication_;
import com.example.mahua.funage.domain.Ticket;
import com.example.mahua.funage.projection.R.layout;
import com.example.mahua.funage.utils.VolleyTools_;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class OrderActivity_
    extends OrderActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_order);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        myApplication = MyApplication_.getInstance();
        volleyTools = VolleyTools_.getInstance_(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static OrderActivity_.IntentBuilder_ intent(Context context) {
        return new OrderActivity_.IntentBuilder_(context);
    }

    public static OrderActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new OrderActivity_.IntentBuilder_(fragment);
    }

    public static OrderActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new OrderActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        tv_no_data = ((TextView) hasViews.findViewById(com.example.mahua.funage.projection.R.id.tv_no_data));
        tv_phone = ((TextView) hasViews.findViewById(com.example.mahua.funage.projection.R.id.tv_phone));
        tv_drama_time = ((TextView) hasViews.findViewById(com.example.mahua.funage.projection.R.id.tv_drama_time));
        tv_address = ((TextView) hasViews.findViewById(com.example.mahua.funage.projection.R.id.tv_address));
        ll_submit = ((LinearLayout) hasViews.findViewById(com.example.mahua.funage.projection.R.id.ll_submit));
        tv_name = ((TextView) hasViews.findViewById(com.example.mahua.funage.projection.R.id.tv_name));
        tv_submit = ((TextView) hasViews.findViewById(com.example.mahua.funage.projection.R.id.tv_submit));
        ll_data = ((LinearLayout) hasViews.findViewById(com.example.mahua.funage.projection.R.id.ll_data));
        lv_orderDetail = ((ListView) hasViews.findViewById(com.example.mahua.funage.projection.R.id.lv_orderDetail));
        tv_drama_name = ((TextView) hasViews.findViewById(com.example.mahua.funage.projection.R.id.tv_drama_name));
        {
            View view = hasViews.findViewById(com.example.mahua.funage.projection.R.id.ll_submit);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        OrderActivity_.this.onSubmit();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.example.mahua.funage.projection.R.id.tv_submit);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        OrderActivity_.this.onSubmit();
                    }

                }
                );
            }
        }
        {
            AdapterView<?> view = ((AdapterView<?> ) hasViews.findViewById(com.example.mahua.funage.projection.R.id.lv_orderDetail));
            if (view!= null) {
                view.setOnItemClickListener(new OnItemClickListener() {


                    @Override
                    public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                        OrderActivity_.this.lv_orderDetailItemClicked(((Ticket) parent.getAdapter().getItem(position)));
                    }

                }
                );
            }
        }
        initData();
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, OrderActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, OrderActivity_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, OrderActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public OrderActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

    }

}
