//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.example.mahua.funage.api;

import android.content.Context;
import android.content.SharedPreferences;
import org.androidannotations.api.sharedpreferences.BooleanPrefEditorField;
import org.androidannotations.api.sharedpreferences.BooleanPrefField;
import org.androidannotations.api.sharedpreferences.EditorHelper;
import org.androidannotations.api.sharedpreferences.SharedPreferencesHelper;
import org.androidannotations.api.sharedpreferences.StringPrefEditorField;
import org.androidannotations.api.sharedpreferences.StringPrefField;

public final class MyPrefs_
    extends SharedPreferencesHelper
{

    private Context context_;

    public MyPrefs_(Context context) {
        super(context.getSharedPreferences((getLocalClassName(context)+"_MyPrefs"), 0));
        this.context_ = context;
    }

    public MyPrefs_.MyPrefsEditor_ edit() {
        return new MyPrefs_.MyPrefsEditor_(getSharedPreferences());
    }

    private static String getLocalClassName(Context context) {
        String packageName = context.getPackageName();
        String className = context.getClass().getName();
        int packageLen = packageName.length();
        if (((!className.startsWith(packageName))||(className.length()<= packageLen))||(className.charAt(packageLen)!= '.')) {
            return className;
        }
        return className.substring((packageLen + 1));
    }

    public BooleanPrefField checkValidated() {
        return booleanField("checkValidated", false);
    }

    public StringPrefField city_id() {
        return stringField("city_id", "");
    }

    public StringPrefField drama_id() {
        return stringField("drama_id", "");
    }

    public BooleanPrefField padValidate() {
        return booleanField("padValidate", false);
    }

    public BooleanPrefField personCardScan() {
        return booleanField("personCardScan", false);
    }

    public StringPrefField theater_id() {
        return stringField("theater_id", "");
    }

    public final static class MyPrefsEditor_
        extends EditorHelper<MyPrefs_.MyPrefsEditor_>
    {


        MyPrefsEditor_(SharedPreferences sharedPreferences) {
            super(sharedPreferences);
        }

        public BooleanPrefEditorField<MyPrefs_.MyPrefsEditor_> checkValidated() {
            return booleanField("checkValidated");
        }

        public StringPrefEditorField<MyPrefs_.MyPrefsEditor_> city_id() {
            return stringField("city_id");
        }

        public StringPrefEditorField<MyPrefs_.MyPrefsEditor_> drama_id() {
            return stringField("drama_id");
        }

        public BooleanPrefEditorField<MyPrefs_.MyPrefsEditor_> padValidate() {
            return booleanField("padValidate");
        }

        public BooleanPrefEditorField<MyPrefs_.MyPrefsEditor_> personCardScan() {
            return booleanField("personCardScan");
        }

        public StringPrefEditorField<MyPrefs_.MyPrefsEditor_> theater_id() {
            return stringField("theater_id");
        }

    }

}
