//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.example.mahua.funage.utils;

import android.content.Context;
import android.net.ConnectivityManager;
import android.net.wifi.WifiManager;

public final class AndroidUtil_
    extends AndroidUtil
{

    private Context context_;

    private AndroidUtil_(Context context) {
        context_ = context;
        init_();
    }

    public static AndroidUtil_ getInstance_(Context context) {
        return new AndroidUtil_(context);
    }

    private void init_() {
        wifiManager = ((WifiManager) context_.getSystemService(Context.WIFI_SERVICE));
        connectivityManager = ((ConnectivityManager) context_.getSystemService(Context.CONNECTIVITY_SERVICE));
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
