//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.example.mahua.funage.utils;

import android.content.Context;
import com.example.mahua.funage.application.MyApplication_;

public final class LogUtil_
    extends LogUtil
{

    private Context context_;

    private LogUtil_(Context context) {
        context_ = context;
        init_();
    }

    public static LogUtil_ getInstance_(Context context) {
        return new LogUtil_(context);
    }

    private void init_() {
        instance = MyApplication_.getInstance();
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
