//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.example.mahua.funage.utils;

import android.content.Context;

public final class VolleyTools_
    extends VolleyTools
{

    private Context context_;

    private VolleyTools_(Context context) {
        super(context);
        context_ = context;
        init_();
    }

    public static VolleyTools_ getInstance_(Context context) {
        return new VolleyTools_(context);
    }

    private void init_() {
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
